services:
  mysql:
    image: mysql:8.0
    container_name: finflow_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finflow_db
      MYSQL_USER: vini
      MYSQL_PASSWORD: vini123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: finflow_api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Use o hostname "mysql" (nome do serviço) no DATABASE_URL
      DATABASE_URL: "mysql://vini:vini123@mysql:3306/finflow_db"
      # Ajuste a porta se seu server.ts ouvir outra
      PORT: "3333"
      JWT_SECRET: "um-segredo-misterioso-e-bem-escondido-bem-aqui" # se usar jwt
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        pnpm prisma generate &&
        pnpm prisma migrate deploy &&
        pnpm dev
      "

volumes:
  mysql_data:
