# Dockerfile.dev
FROM node:20-alpine

# Instala pnpm
RUN corepack enable && corepack prepare pnpm@10.11.0 --activate

WORKDIR /app

# Instala deps primeiro para aproveitar cache
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

# Copia o resto do projeto
COPY . .

EXPOSE 3333
# O comando final é definido no compose (para poder rodar prisma antes)
